### ISSUE TITLE
About Figure 3, some questions

### ISSUE THREAD

**Issue by floatingstarZ** [AI4LIFE-GROUP/SpLiCE#4]
Hello, author. I have some questions about Figure 3 and I hope to get some clarification. 1. Is the cosine similarity between img-img pairs obtained by randomly selecting two images? 2. How is the cosine similarity between img-text pairs obtained? Is it for each image with its corresponding text or is it random? 3. After mean-centering, the cosine similarity between text-img pairs seems to be lower, as if the two are no longer in the same space. What is the significance of mean-centering?

**Comment by alex-oesterling** [comment]
Hi! 

1) We compute cosine similarity over ALL pairs of (images, images), (text, text), (images, text), for all samples in MSCOCO. This is how we construct the histogram you observe in Fig. 3. This includes paired and unpaired images/text, which is why the image-text histogram has a little bump at the right side of the axis for the correctly paired images/text. (note that out of n^2 pairs, only n are correct pairs.) 

2) We compute similarity between image and text by taking the clip embeddings of each image and text and then computing cosine similarity as they are both 512-dimensional vectors.

3) After mean-centering, the similarity is lower meaning the image/text embedding vectors are well-distributed on the entire hypersphere instead of being concentrated with a high similarity. Its not that the two are no longer in the same space, but on average, these vectors are orthogonal to each other indicating a better behaving distribution over the entire hypersphere.

The significance of mean-centering is to ensure our concepts span the entire 512-dimensional space allowing for the use of sparse coding with the concept dictionary.

I hope this answers your questions!
